name: Deploy ARM Template and Run Azure PowerShell Commands

on:
  workflow_dispatch:
   



jobs:

  deploy-and-run:
    runs-on: ubuntu-latest
    environment: qa
    steps:
    - name: Create Azure cred variable 
      run: |
          AzureCreds=$(echo '{"clientId": "${{secrets.AZURE_CLIENT_ID}}", "clientSecret": "${{secrets.AZURE_CLIENT_SECRET}}", "subscriptionId": "${{secrets.AZURE_SUBSCRIPTION_ID}}", "tenantId": "${{secrets.AZURE_TENANT_ID}}" }' | jq -c .)
          echo "AzureCreds=$AzureCreds" >> $GITHUB_ENV

    - uses: azure/login@v1
      with:
        creds: ${{ env.AzureCreds }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use variables
      run: |
        echo "rg variable : ${{ vars.RESOURCE_GROUP_NAME }}"

    - name: Deploy ARM Template
      uses: azure/arm-deploy@v1
      with:
        subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resource-group: ${{ vars.RESOURCE_GROUP_NAME }}
        template: deploy.json
        parameters: parameters.json

   
