name: Test
on:
  workflow_dispatch:

jobs:
  display-variables:
    name: Test
    
    runs-on: ubuntu-latest
    environment: qa
    steps:
    - name: Use variables
      run: |
        echo "repository variable : ${{ vars.RESOURCE_GROUP_NAME }}"
       
       
        
       
