name: Test
on:
  workflow_dispatch:
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.RESOURCE_GROUP_NAME }}

jobs:
  display-variables:
    name: Test
    
    runs-on: ubuntu-latest
   
    steps:
    - name: Use variables
      run: |
        echo "repository variable : $REPOSITORY_VAR"
       
      env:
        REPOSITORY_VAR: ${{ vars.RESOURCE_GROUP_NAME }}
       
