name: VM Tag Update

on:
  workflow_dispatch:



jobs:
  deploy-and-run:
    runs-on: ubuntu-latest
    environment: qa
    steps:
       - name: Checkout repository
         uses: actions/checkout@v2
        
       - name: Create Azure cred variable
         run: |
          AzureCreds=$(echo '{"clientId": "${{secrets.AZURE_CLIENT_ID}}", "clientSecret": "${{secrets.AZURE_CLIENT_SECRET}}", "subscriptionId": "${{secrets.AZURE_SUBSCRIPTION_ID}}", "tenantId": "${{secrets.AZURE_TENANT_ID}}"}' | jq -c .)
          echo "AzureCreds=$AzureCreds" >> $GITHUB_ENV
          logicAppName=$(jq -r '.parameters.LogicAppName.value' parameters.json)
          echo "LogicAppName=$logicAppName" >> $GITHUB_ENV
          automationAccountName=$(jq -r '.parameters.AutomationAccountName.value' parameters.json)
          echo "AutomationAccountName=$automationAccountName" >> $GITHUB_ENV

       - uses: azure/login@v1
         with:
          creds: ${{ env.AzureCreds }}
          
       - name: Run script
         run: |
          #!/bin/bash
          file="vm_list.csv"
          tail -n +2 "$file" | while IFS= read -r line || [ -n "$line" ]; do
              vm_name=$(echo "$line" | cut -d ',' -f 1)
              rg_name=$(echo "$line" | cut -d ',' -f 2)
              sub_name=$(echo "$line" | cut -d ',' -f 3)
              tag_value=$(echo "$line" | cut -d ',' -f 4)
              tag_name="Patch_Schedule"
              resource_id="/subscriptions/$(az account show --subscription \"$sub_name\" --query 'id' --output tsv)/resourceGroups/$rg_name/providers/Microsoft.Compute/virtualMachines/$vm_name"
              az resource tag --ids "$resource_id" --tags $tag_name="$tag_value"

          done 
