name: VM Tag Update

on:
  workflow_dispatch:



jobs:
  deploy-and-run:
    runs-on: ubuntu-latest
    environment: qa
    steps:
       - name: Checkout repository
         uses: actions/checkout@v2
        
       - name: Create Azure cred variable
         run: |
          AzureCreds=$(echo '{"clientId": "${{secrets.AZURE_CLIENT_ID}}", "clientSecret": "${{secrets.AZURE_CLIENT_SECRET}}", "subscriptionId": "${{secrets.AZURE_SUBSCRIPTION_ID}}", "tenantId": "${{secrets.AZURE_TENANT_ID}}"}' | jq -c .)
          echo "AzureCreds=$AzureCreds" >> $GITHUB_ENV
          logicAppName=$(jq -r '.parameters.LogicAppName.value' parameters.json)
          echo "LogicAppName=$logicAppName" >> $GITHUB_ENV
          automationAccountName=$(jq -r '.parameters.AutomationAccountName.value' parameters.json)
          echo "AutomationAccountName=$automationAccountName" >> $GITHUB_ENV

       - uses: azure/login@v1
         with:
          creds: ${{ env.AzureCreds }}
       - name: Convert Excel to CSV
         uses: microsoft/excel-to-csv-action@v1
         with:
          excel-file: vm_list.xlsx
          csv-file: vm_list.csv
       - name: Run script
         run: |
          #!/bin/bash
          csv_file="vm_list.csv"

          # Skip the first row (header) and loop through the CSV file, extracting specific columns
          
          { read -r; while IFS=, read -r vm_name resource_group_name subscription_name new_tag_value; do
            # Construct the resource ID based on the provided information
            resource_id="/subscriptions/$(az account show --subscription $subscription_name --query 'id' --output tsv)/resourceGroups/$resource_group_name/providers/Microsoft.Compute/virtualMachines/$vm_name"

             echo "$resource_id"
          done; } < "$csv_file"
